In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=['this is the data science class with SL',
       'AI is the next class',
       'and this is the next class',
       'and this is fourth class']

#### Vocabulary Size

In [3]:
vocab_size=10000

#### One hot representation

In [6]:
onehot_repr=[one_hot(words,vocab_size)for words in sent]
print(onehot_repr)

[[7805, 7511, 273, 3740, 1708, 2612, 5534, 3578], [6809, 7511, 273, 4502, 2612], [630, 7805, 7511, 273, 4502, 2612], [630, 7805, 7511, 1832, 2612]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences # To ensure that all sequences have the same length, padding is applied.
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
embeded_docs=pad_sequences(onehot_repr,padding='pre')
embeded_docs

array([[7805, 7511,  273, 3740, 1708, 2612, 5534, 3578],
       [   0,    0,    0, 6809, 7511,  273, 4502, 2612],
       [   0,    0,  630, 7805, 7511,  273, 4502, 2612],
       [   0,    0,    0,  630, 7805, 7511, 1832, 2612]])

In [10]:
sent_lenght=10
embeded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_lenght)# The padding='post' argument indicates that padding should be added at the end of the sequences.
embeded_docs

array([[   0,    0, 7805, 7511,  273, 3740, 1708, 2612, 5534, 3578],
       [   0,    0,    0,    0,    0, 6809, 7511,  273, 4502, 2612],
       [   0,    0,    0,    0,  630, 7805, 7511,  273, 4502, 2612],
       [   0,    0,    0,    0,    0,  630, 7805, 7511, 1832, 2612]])

In [11]:
dim=15 #features

In [13]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_lenght))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 15)            150000    
                                                                 
Total params: 150000 (585.94 KB)
Trainable params: 150000 (585.94 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embeded_docs)

1/1 [==============================] - 2s 2s/step


array([[[ 0.00981467, -0.02605823, -0.04042778, -0.00625418,
         -0.00459597,  0.00450872, -0.01163217, -0.04494091,
         -0.03473251,  0.04800114,  0.01156517,  0.01347378,
         -0.0092049 ,  0.03603161,  0.00745047],
        [ 0.00981467, -0.02605823, -0.04042778, -0.00625418,
         -0.00459597,  0.00450872, -0.01163217, -0.04494091,
         -0.03473251,  0.04800114,  0.01156517,  0.01347378,
         -0.0092049 ,  0.03603161,  0.00745047],
        [-0.04051368,  0.012773  ,  0.0338015 , -0.04238247,
          0.04311654,  0.03111375,  0.01341817,  0.03726763,
          0.02845254, -0.00802962, -0.04012851,  0.01867909,
         -0.04885064,  0.04801296, -0.04642698],
        [-0.01971904,  0.04467038, -0.04162056,  0.04111382,
          0.02811085, -0.01619865,  0.00829991,  0.04148744,
          0.02075908,  0.00815945, -0.03203025,  0.03011924,
         -0.00290617,  0.01515825, -0.00516853],
        [ 0.03368105, -0.02038686,  0.0322335 , -0.01448864,
         -0

In [17]:
embeded_docs[0]

array([   0,    0, 7805, 7511,  273, 3740, 1708, 2612, 5534, 3578])

In [16]:
model.predict(embeded_docs[0])

1/1 [==============================] - 0s 58ms/step


array([[ 0.00981467, -0.02605823, -0.04042778, -0.00625418, -0.00459597,
         0.00450872, -0.01163217, -0.04494091, -0.03473251,  0.04800114,
         0.01156517,  0.01347378, -0.0092049 ,  0.03603161,  0.00745047],
       [ 0.00981467, -0.02605823, -0.04042778, -0.00625418, -0.00459597,
         0.00450872, -0.01163217, -0.04494091, -0.03473251,  0.04800114,
         0.01156517,  0.01347378, -0.0092049 ,  0.03603161,  0.00745047],
       [-0.04051368,  0.012773  ,  0.0338015 , -0.04238247,  0.04311654,
         0.03111375,  0.01341817,  0.03726763,  0.02845254, -0.00802962,
        -0.04012851,  0.01867909, -0.04885064,  0.04801296, -0.04642698],
       [-0.01971904,  0.04467038, -0.04162056,  0.04111382,  0.02811085,
        -0.01619865,  0.00829991,  0.04148744,  0.02075908,  0.00815945,
        -0.03203025,  0.03011924, -0.00290617,  0.01515825, -0.00516853],
       [ 0.03368105, -0.02038686,  0.0322335 , -0.01448864, -0.00813914,
         0.00197442,  0.04208576,  0.00014595, 