In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [7]:
adm= pd.read_csv('admission.csv')

In [8]:
adm.head()

ADMIT  GRE   GPA  RANK
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

In [9]:
adm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ADMIT   400 non-null    int64  
 1   GRE     400 non-null    int64  
 2   GPA     400 non-null    float64
 3   RANK    400 non-null    int64  
dtypes: float64(1), int64(3)
memory usage: 12.6 KB


In [10]:
adm.isnull().sum()

ADMIT    0
GRE      0
GPA      0
RANK     0
dtype: int64

In [11]:
adm.shape

(400, 4)

In [12]:
adm.size

1600

In [13]:
features= adm.drop('ADMIT',axis=1)

In [14]:
target= adm[['ADMIT']]

In [15]:
x_train,x_test,y_train,y_test= train_test_split(features,target,train_size=0.75,random_state=100)

In [17]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)


(300, 3)
(300, 1)
(100, 3)
(100, 1)


In [18]:
log_model= LogisticRegression()

In [22]:
log_model.fit(x_train,y_train)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [23]:
log_model.predict_proba(x_test)

array([[0.68252193, 0.31747807],
       [0.87744779, 0.12255221],
       [0.48256058, 0.51743942],
       [0.86679746, 0.13320254],
       [0.93027558, 0.06972442],
       [0.69139854, 0.30860146],
       [0.61164889, 0.38835111],
       [0.82789895, 0.17210105],
       [0.78305594, 0.21694406],
       [0.73953192, 0.26046808],
       [0.88266987, 0.11733013],
       [0.58036674, 0.41963326],
       [0.84853288, 0.15146712],
       [0.73136097, 0.26863903],
       [0.62976917, 0.37023083],
       [0.86314428, 0.13685572],
       [0.58562528, 0.41437472],
       [0.88252094, 0.11747906],
       [0.82980417, 0.17019583],
       [0.83263704, 0.16736296],
       [0.87632849, 0.12367151],
       [0.70645687, 0.29354313],
       [0.60348332, 0.39651668],
       [0.52062454, 0.47937546],
       [0.53629978, 0.46370022],
       [0.77364866, 0.22635134],
       [0.74850836, 0.25149164],
       [0.71602515, 0.28397485],
       [0.81709857, 0.18290143],
       [0.84547159, 0.15452841],
       [0.

### thershold value

In [85]:
y_pred_new= [0 if x[0]>0.6 else 1 for x in log_model.predict_proba(x_test)]

In [86]:
y_pred= log_model.predict(x_test)

In [87]:
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [88]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [89]:
accuracy_score(y_test,y_pred_new)

0.64

In [90]:
confusion_matrix(y_test,y_pred_new)

array([[50, 14],
       [22, 14]], dtype=int64)

In [91]:
print(classification_report(y_test,y_pred_new))

              precision    recall  f1-score   support

           0       0.69      0.78      0.74        64
           1       0.50      0.39      0.44        36

    accuracy                           0.64       100
   macro avg       0.60      0.59      0.59       100
weighted avg       0.62      0.64      0.63       100



In [92]:
precision= 58/(58+31)
precision

0.651685393258427

In [93]:
y_test.value_counts()

ADMIT
0        64
1        36
dtype: int64

In [94]:
log_model.score(x_test,y_test)

0.63