In [1]:
import numpy as np

In [2]:
one_dim= np.array([1,2,3,4,5])

In [3]:
one_dim

array([1, 2, 3, 4, 5])

In [4]:
one_dim.ndim

1

In [5]:
one_dim.shape

(5,)

In [6]:
one_dim.size

5

In [8]:
type(one_dim)

numpy.ndarray

In [9]:
# accessing elements in an array

In [10]:
one_dim[0]

1

In [11]:
one_dim[1]

2

In [12]:
one_dim[4]=100

In [13]:
one_dim

array([  1,   2,   3,   4, 100])

In [16]:
one_dim[0:4]=[10,20,30,40]

In [17]:
one_dim

array([ 10,  20,  30,  40, 100])

In [19]:
# delete the element from an array
np.delete(one_dim,4,axis=0)

array([10, 20, 30, 40])

In [31]:
arr=np.delete(one_dim,(1,2,3),axis=0)

In [32]:
arr

array([ 10, 100])

In [33]:
one_dim= np.arange(1,10,2)

In [34]:
one_dim

array([1, 3, 5, 7, 9])

In [36]:
two_dim= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [37]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
two_dim.ndim

2

In [39]:
two_dim.shape

(3, 3)

In [40]:
two_dim.size

9

In [41]:
two_dim[2,2]

9

In [42]:
two_dim[1,2]

6

In [45]:
two_dim[0:3:2,0:2]

array([[1, 2],
       [7, 8]])

In [44]:
two_dim[0:3,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [46]:
two_dim


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
# row replacement
two_dim[2:3]=[10,20,30]

In [50]:
two_dim

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [59]:
# column replacement
two_dim[:,2]=[100,200,300]

In [56]:
two_dim

array([[  1,   2, 100],
       [  4,   5, 200],
       [ 10,  20, 300]])

In [61]:
np.delete(two_dim,2,axis=0)

array([[  1,   2, 100],
       [  4,   5, 200]])

In [62]:
np.delete(two_dim,2,axis=1)

array([[ 1,  2],
       [ 4,  5],
       [10, 20]])

In [63]:
two_dim= np.arange(0,12).reshape(3,4)

In [64]:
two_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
np.random.randint(1,10,100)

array([2, 4, 1, 3, 1, 3, 5, 6, 5, 8, 6, 3, 3, 3, 6, 3, 1, 9, 1, 8, 5, 3,
       9, 1, 2, 6, 6, 2, 1, 5, 8, 2, 9, 4, 9, 6, 4, 9, 2, 5, 3, 3, 9, 1,
       5, 2, 3, 2, 9, 8, 9, 7, 9, 3, 3, 9, 4, 4, 9, 6, 4, 1, 2, 9, 1, 6,
       4, 7, 9, 3, 4, 2, 5, 3, 7, 6, 5, 6, 9, 1, 5, 6, 5, 5, 8, 7, 6, 7,
       2, 4, 8, 3, 3, 7, 5, 3, 6, 9, 7, 2])

In [75]:
two_ran= np.random.randint(1,10,16).reshape(4,4)

In [76]:
two_ran

array([[1, 6, 4, 5],
       [2, 9, 4, 7],
       [2, 2, 9, 8],
       [3, 9, 7, 3]])

In [68]:
two_ran= np.random.randint(1,10,[4,3])

In [69]:
two_ran

array([[9, 5, 6],
       [4, 9, 7],
       [3, 8, 7],
       [9, 7, 5]])

In [71]:
np.random.rand(100)

array([0.49603675, 0.61366953, 0.15376368, 0.65884533, 0.25429546,
       0.39245114, 0.22628864, 0.31672629, 0.6169807 , 0.13716407,
       0.62219327, 0.41066182, 0.78206946, 0.36995657, 0.67269394,
       0.02968705, 0.60014365, 0.10083173, 0.43875715, 0.66142722,
       0.2371889 , 0.24643722, 0.19940223, 0.51249058, 0.62039898,
       0.22424424, 0.93661803, 0.02922303, 0.20260386, 0.44223878,
       0.63231163, 0.5050541 , 0.92121564, 0.89035435, 0.82677424,
       0.18534052, 0.03142693, 0.99434662, 0.49455786, 0.06462036,
       0.81572463, 0.48373515, 0.49035504, 0.79645882, 0.54119919,
       0.6473808 , 0.13734436, 0.27544795, 0.58782299, 0.13530431,
       0.17603833, 0.12392807, 0.46144895, 0.68798716, 0.81425732,
       0.84142119, 0.84851851, 0.11629791, 0.19668261, 0.52994509,
       0.60125635, 0.48329546, 0.62512192, 0.96123822, 0.08957571,
       0.95081188, 0.69747298, 0.7404883 , 0.07269905, 0.97024172,
       0.93657275, 0.88617409, 0.66585489, 0.16097292, 0.30333

In [72]:
two_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
two_dim.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [82]:
# inverted matrix of two_ran
np.linalg.inv(two_ran)

array([[-1.56902357,  0.82491582,  0.19191919,  0.17845118],
       [ 0.25925926, -0.07407407, -0.11111111,  0.03703704],
       [ 0.38383838, -0.34343434,  0.03030303,  0.08080808],
       [-0.1043771 ,  0.1986532 ,  0.07070707, -0.14478114]])

In [83]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
np.zeros(shape=(3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
a= np.array([[1,2],[3,4]])

In [86]:
b=np.array([[5,6],[7,8]])

In [87]:
a

array([[1, 2],
       [3, 4]])

In [94]:
b

array([[5, 6],
       [7, 8]])

In [89]:
# matrix arithmetic

In [90]:
a*b

array([[ 5, 12],
       [21, 32]])

In [91]:
# matrix multiplication
a@b

array([[19, 22],
       [43, 50]])

In [92]:
a+b

array([[ 6,  8],
       [10, 12]])

In [93]:
a-b

array([[-4, -4],
       [-4, -4]])

## Three dimensional array